# Generated by Django 2.2.5 on 2022-11-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221031_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
