# Generated by Django 4.1.3 on 2022-11-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_certificate_certificate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_alt_description',
            field=models.TextField(null=True),
        ),
    ]
