# Generated by Django 4.1.3 on 2022-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_category_alt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
